version: 0.2

env:
  variables:
    buildComputeType: BUILD_GENERAL1_SMALL
    buildImage: 964010022385.dkr.ecr.eu-central-1.amazonaws.com/releases/base/images/alpine/alpine-3-15/dind/dind-20-10/gradle/gradle-7-4/openjdk-11-dind:1.1.8
    GROUP_ID: 'base/images/debian/debian-11-bullseye/gradle/gradle-7-4/graalvm-ce-17'
    ARTIFACT_ID: 'graalvm-17-gradle-7-4'
    IMAGE_TAG: '1.0.1'

phases:
  install:
    commands:
      - /home/image/check.sh
      - /usr/local/bin/dockerd-entrypoint.sh
  pre_build:
    commands:
      - /home/docker/login.sh
      - . /home/aws/codeartifact.sh
  build:
    commands:
      - echo $CI_COMMIT_TAG
      - echo $IMAGE_TAG
      - echo Building the Docker image...
      - COORDINATES=$HOST/$GROUP_ID/$ARTIFACT_ID
      - echo $COORDINATES
      - docker build -t $COORDINATES:$IMAGE_TAG .
      - docker tag $COORDINATES:$IMAGE_TAG $COORDINATES:latest
  post_build:
      commands:
        - echo Push Docker image tags $IMAGE_TAG and latest
        - docker image push --all-tags $COORDINATES --quiet
