version: 0.2

env:
  variables:
    buildComputeType: BUILD_GENERAL1_SMALL
    buildImage: 964010022385.dkr.ecr.eu-central-1.amazonaws.com/releases/base/images/alpine/alpine-3-15/dind/dind-20-10/gradle/gradle-7-4/openjdk-11-dind:1.2.0

phases:
  install:
    commands:
      - /home/image/check.sh
      - /usr/local/bin/dockerd-entrypoint.sh
  pre_build:
    commands:
      - /home/aws/ecr/login.sh
      - . /home/aws/codeartifact/login.sh
  build:
    commands:
      - /home/git/find-current-branch.sh
      - ./gradle/docker-push.sh
