version: 0.2

env:
  variables:
    buildComputeType: BUILD_GENERAL1_SMALL
    buildImage: 964010022385.dkr.ecr.eu-central-1.amazonaws.com/releases/base/images/alpine/alpine-3-15/dind/dind-20-10/gradle/gradle-7-4/openjdk-11-dind:1.1.8

phases:
  install:
    commands:
      - /home/image/check.sh
      - /usr/local/bin/dockerd-entrypoint.sh
  pre_build:
    commands:
      - /home/docker/login.sh
      - . /home/aws/codeartifact.sh
  build:
    commands:
      - /home/git/find-current-branch.sh
      - CURRENT_TAG=$(git tag --points-at HEAD | tail -1)
      - |
        if [ -n "$CURRENT_TAG" ]
        then
          gradle dockerPush
          /home/gradle/summary.sh
        else
          echo "INFO: No git tag found for this commit."
          echo "INFO: You see this message because no snapshot repository was set up for this project."
          echo "INFO: to avoid this message, execute: ./bump.zsh locally."
        fi