version: 0.2

env:
  variables:
    buildComputeType: BUILD_GENERAL1_SMALL
    buildImage: 964010022385.dkr.ecr.eu-central-1.amazonaws.com/releases/base/images/alpine/alpine-3-15/dind/dind-20-10/alpine-3-15-dind:1.0.3
    GROUP_ID: 'base/images/debian/debian-11-bullseye/gradle/gradle-7-4/graalvm-ce-17'
    ARTIFACT_ID: 'graalvm-17-gradle-7-4'
    IMAGE_TAG: '1.0.1'

phases:
  pre_build:
    commands:
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $HOST
  build:
    commands:
      - echo $CI_COMMIT_TAG
      - echo $IMAGE_TAG
      - echo Building the Docker image...
      - COORDINATES=$HOST/$GROUP_ID/$ARTIFACT_ID
      - echo $COORDINATES
      - docker build -t $COORDINATES:$IMAGE_TAG .
      - docker tag $COORDINATES:$IMAGE_TAG $COORDINATES:latest
  post_build:
      commands:
        - echo Push Docker image tags $IMAGE_TAG and latest
        - docker image push --all-tags $COORDINATES --quiet
